config/routes.rb
RrBlog::Application.routes.draw do
  resources :photos

  resources :albums

  devise_for :users, :path_names => { :sign_up => "register" } 

  resources :posts do
    resources :comments
  end
  
  get "home/index"
  
  root :to => 'posts#index'
  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  
    # Uses Paperclip gem to allow uploads to Photo model
    has_attached_file :image, :styles => { :medium => "800x600>", :thumb => "200x200>" },
                      :url  => "/assets/photos/:id/:style/:basename.:extension",
                      :path => ":rails_root/public/assets/photos/:id/:style/:basename.:extension"
                      
    validates_attachment_presence :image

  #   before_save :destroy_image?
  # 
  #   def image_delete
  #     @image_delete ||= "0"
  #   end
  # 
  #   def image_delete=(value)
  #     @image_delete = value
  #   end
  # 
  # private
  #   def destroy_image?
  #     self.image.clear if @image_delete == "1"
  #   end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new( params[:photo] )

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, :notice => 'Photo was successfully created.' }
        format.json { render :json => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, :notice => 'Photo was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo, :html => { :multipart => true }) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>    
  </div>
  
  <div class="field">
    <b>Photo</b><br/>
    <%= image_tag @photo.image :thumb %><br/>
    <%= f.file_field :image  %>
  </div>

  <div class="field">
    <b>Album</b><br/>   
    <%= select("photo", "album_id", Album.all.collect {|a| [ a.title, a.id ] }, { :include_blank => "--Choose An Album--" }) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= debug @photo %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= image_tag photo.image.url(:thumb) %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Picture</b><br/>
  <%= image_tag @photo.image.url%>
</p>

<p>
  <b>Album</b><br/>
  <%= @photo.album.title %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>